
export const productsList = [
    'iPhone 12',
    'iPhone 12 Mini',
    'iPhone 12 Pro Max',
    'iPhone 12 Pro',
    'iPhone 11',
    'iPhone 11 Pro',
    'iPhone XS',
    'iPhone XR',
    'iPhone XS Max',
    'Galaxy S20',
    'Galaxy S20+',
    'Galaxy S20 Ultra',
    'Galaxy S10',
    'Galaxy S9',
    'Galaxy Note 20',
    'Galaxy Note 20 Ultra',
    'Pixel 4',
    'Pixel 3',
    'Pixel 2',
    'One Plus 8',
    'One Plus 8T',
    'One Plus 8 Pro',
    'One Plus 7T',
    'One Plus 7',
    'One Plus 6T'        
];